name: test

on:
  push:
    branches: main

permission:
 contents: read
 checks: write
pull-requests: write

jobs:
 build:
  pull-requests: ubuntu-latest

  steps:
  - name: Checkout code
    uses:
  - name: Setup JDK 21
    uses:
    with:
      java version: "21"
      distribution: "temurin"
      cache: "gradle"

  - name: Grant execute permission for gradlew
    run: chmod +x gradlew

  - name: Build with Gradle
    run:  ./gradlew build

  - name:
    run:
    



      
